spring.application.name=pdfscanner

spring.datasource.url=jdbc:postgresql://localhost:5432/pdfscanner_db
spring.datasource.username=zhappar_a

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

bucket4j.enabled=false

secret.key:d4MXfU8PmMDHyDrmNp8GuyJHsSxBHs7x5rUKkN3APOw

tess.path=tesseract
